title: William's projects
description: This is a page for all of my projects. You can view them individually or you can look at the whole project repo in the link below.
show_downloads: false
google_analytics: true
theme: jekyll-theme-minimal
